roles = [
    "wr1", 
    "wr2", 
    "wr3", 
    "rb1", 
    "rb2", 
    "qb1",
    "rest"
]

fields = [
    "passCmp",
    "passAtt",
    "passYds",
    "passTd",
    "passInt",
    "passLong",
    "passRating",
    "passTargetYds",
    # passPoor_throws": number,
    # passBlitzed: number,
    # passHurried: number,
    # passScrambles: number,
    "rushAtt",
    "rushYds",
    "rushTd",
    "rushLong",
    "rushYdsBc",
    "rushYdsAc",
    "rushBrokenTackles",
    "recAtt",
    "recCmp",
    "recYds",
    "recTd",
    "recDrops",
    "recLong",
    "recDepth",
    "recYac",
    "sacked",
    "fumbles",
    "fumblesLost",
]
